---
- hosts: localhost
  connection: local
  roles:
    - role: tkimball83.iterm2
      iterm2_defaults:
        - name: OnlyWhenMoreTabs
          type: string
          value: 0
        - name: PromptOnQuit
          type: bool
          value: false
  tasks:
  - name: Install chrome
    command: brew cask install google-chrome

  - name: Install Shiftif
    command: brew cask install shiftit

  - name: Install Sublime Text
    command: brew cask install sublime-text

  - name: Install mas cli
    command: brew install mas

  - name: Install wechat
    # needs login to mac store
    command: mas lucky wechat

  - name: Install krypton
    command: brew install kryptco/tap/kr

  - name: Download alfred source code
    register: alfred_source_downloaded
    get_url: dest=~/Downloads url={{alfred_source_url}}
